# Generated by Django 3.0.6 on 2020-05-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='My full name.', max_length=100)),
                ('phone', models.CharField(help_text='My phone number.', max_length=100)),
                ('email', models.CharField(help_text='My email address.', max_length=100)),
                ('url', models.CharField(help_text='My website address.', max_length=100)),
                ('sort_order', models.FloatField(default=10, help_text='Order in which this entry is displayed.')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkHistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='The employer for whom I worked.', max_length=200)),
                ('title', models.CharField(help_text='Title I held at this company.', max_length=200)),
                ('location', models.CharField(help_text='Location in which the company is located.', max_length=200)),
                ('contract', models.BooleanField(default=False, help_text='A flag indicating whether I was a contractor.')),
                ('timespan', models.CharField(help_text='Timespan in which I worked at the company.', max_length=200)),
                ('sort_order', models.FloatField(default=10, help_text='Order in which this entry is displayed.')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='A description of the achievement accomplished.')),
                ('sort_order', models.FloatField(default=10, help_text='Order in which this entry is displayed.')),
                ('entry', models.ForeignKey(help_text='Work history entry to which this achievement belongs.', on_delete=django.db.models.deletion.CASCADE, to='resume.WorkHistoryEntry')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this project.', max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='Short description of the project.', max_length=200)),
                ('long_description', models.TextField(help_text='Long description of the project.')),
                ('deployment_url', models.URLField(blank=True, help_text='URL of the deployed project (if a web app).', null=True)),
                ('src_url', models.URLField(blank=True, help_text='URL to source code of the project.', null=True)),
                ('sort_order', models.FloatField(default=10, help_text='Order in which this entry is displayed.')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProfileEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(help_text='Entry in my profile.', max_length=500)),
                ('sort_order', models.FloatField(default=10, help_text='Order in which this entry is displayed.')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the URL.', max_length=200)),
                ('url', models.URLField(blank=True, help_text='Address of this important URL.', null=True)),
                ('sort_order', models.FloatField(default=10, help_text='Order in which this entry is displayed.')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(help_text='A section of expertise.', max_length=500)),
                ('entry_details', models.TextField(help_text='Details on this expertise.')),
                ('sort_order', models.FloatField(default=10, help_text='Order in which this entry is displayed.')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
